---
all:
  vars:
    ansible_user: root
  children:
    proxmox:
      hosts:
        pve:
          ansible_host: 192.168.15.101
    nas:
      hosts:
        samba:
          ansible_host: 192.168.15.150
          pct_id: 150
    media:
      hosts:
        jellyfin:
          ansible_host: 192.168.15.102
          pct_id: 100
        arr:
          ansible_host: 192.168.15.103
          pct_id: 101
        bookorbit:
          ansible_host: 192.168.15.105
          pct_id: 102
    proxy:
      hosts:
        traefik:
          ansible_host: 192.168.15.104
          pct_id: 104
    databases:
      hosts:
        databases:
          ansible_host: 192.168.15.151
          pct_id: 151
