apiVersion: v1
kind: Secret
metadata:
  name: bookorbit-env
  labels:
    app.kubernetes.io/name: bookorbit
    {{- include "bookorbit.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
